### PR TITLE
Update WncController.cpp

### PR DESCRIPTION
**Pull request by ghost**
removing GPLv3

### CODE REVIEW

**Comment by jflynn129** [comment]
@focalplane I updated with a new routine and left the original code in for you to compare, but it is your code so I don't want to be the final say on merging it back in. Please look it over and if you agree, can you remove the #if 0 code and do the merge?

**Comment by focalplane** [comment]
Hi,  The newer implementation is likely slower than the original that is
GPL3, the prior uses both / and %.  If you think the newer 1 is fast enough
for your purposes it is functionally equivalent as far as I can tell for
the answer/output.

Regards,
-Fred

**Comment by focalplane** [comment]
I am not going to be abke to make time to do any testing so I don’t see why
you want me to remove the preprocessor directive.  I’m fine with the
change, so go ahead!

Thanks!

**Comment by focalplane** [comment]
You have changed the code in the past and have already made this change but
I understand.

Have a good weekend!

**Pull request merged**
